#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "NeivaWeatherCycle.h"
#include "NeivaWeather.generated.h"

class UInstancedStaticMeshComponent;
class UMaterialParameterCollection;
class UMaterialParameterCollectionInstance;
class UDirectionalLightComponent;
class USkyAtmosphereComponent;

UENUM(BlueprintType)
enum class ENeivaWeatherMode : uint8 { Cycle, Dry, Rain };

// One local precipitation field, independent of the possessed pawn type.
// Assets are generated by Scripts/prepare_weather_editor.py before packaging.
UCLASS()
class NEIVAABIERTA_API ANeivaWeather : public AActor
{
    GENERATED_BODY()
public:
    ANeivaWeather();
    virtual void BeginPlay() override;
    virtual void Tick(float DeltaSeconds) override;
    virtual void EndPlay(const EEndPlayReason::Type Reason) override;

    UFUNCTION(BlueprintCallable, Category="Neiva|Weather") void SetWeatherMode(ENeivaWeatherMode Mode);
    UFUNCTION(BlueprintPure, Category="Neiva|Weather") float GetRainAmount() const;
    UFUNCTION(BlueprintPure, Category="Neiva|Weather") float GetWetness() const;
    UFUNCTION(BlueprintPure, Category="Neiva|Weather") FString GetPhaseLabel() const;
    UFUNCTION(BlueprintPure, Category="Neiva|Weather") float GetSecondsUntilChange() const;
    int32 GetRainInstanceCount() const;
    bool IsWeatherReady() const { return bReady; }

private:
    UPROPERTY() TObjectPtr<UInstancedStaticMeshComponent> RainInstances;
    UPROPERTY() TObjectPtr<UMaterialParameterCollection> Parameters;
    UPROPERTY() TObjectPtr<UMaterialParameterCollectionInstance> ParameterInstance;
    UPROPERTY() TObjectPtr<UDirectionalLightComponent> Sun;
    UPROPERTY() TObjectPtr<USkyAtmosphereComponent> Atmosphere;
    FLinearColor DrySunColor = FLinearColor::White;
    float DrySunLux = 0;
    float DryMieScale = 1;
    float DryMieAnisotropy = .8f;
    float LastAtmosphereRain = -1;

    struct FColumn
    {
        FIntPoint Key = FIntPoint(MAX_int32, MAX_int32);
        float GroundZ = 0;
        bool bGroundFound = false;
        bool bNeedsTrace = true;
    };
    TArray<FColumn> Columns;
    NeivaWeather::Cycle Cycle;
    FVector FieldCenter = FVector::ZeroVector;
    FIntPoint GridCenter = FIntPoint(MAX_int32, MAX_int32);
    int32 DropsPerColumn = 6;
    int32 TraceCursor = 0;
    float FieldUpdateSeconds = 0;
    float RefreshSeconds = 0;
    bool bReady = false;

    void UpdateField(const FVector& Position, bool bForce);
    void UpdateColumn(int32 Index);
    void TraceColumns(int32 Budget);
    void PublishParameters();
    void FindAtmosphere();
    void UpdateAtmosphere(bool bRestore = false);
};
